### ISSUE TITLE
Comment Actions column

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#105]
Try to get_actions with ob_get_contents from WP.

**Comment by engelen** [comment]
Done https://github.com/codepress/codepress-admin-columns/commit/3d17aab6f35287a41d77834f3f80c1011670cf51. Furthermore, a new comment row added through the WordPress admin AJAX reply functionality now correctly displays all columns https://github.com/codepress/codepress-admin-columns/commit/63d06b20a9bab676d13a70f4188a496f98536654.
