### ISSUE TITLE
WooCommerce Addon: Order status for WC 2.3

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#129]
Order status has been changed in 2.3. Partially fixed, but it the returned raw_value is 'processing' instead of 'wc-processing'. Needs fix.

**Comment by engelen** [comment]
Fixed https://github.com/codepress/admin-columns-pro/commit/aa67b6241bf9f6487fbd74c26d59b9653bcd1feb. The same raw value is still passed by the `get_raw_value`-method, but the method for retrieving the editability value now prepends "wc-" to the order status.
