### ISSUE TITLE
WooCommerce Addon: placement edit icon

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#132]
The edit icon should be placed after the title.

note: Once you edit the title, the icon is placed correctly.

![icon](https://cloud.githubusercontent.com/assets/2736280/6414529/7402eb88-be98-11e4-87f6-ff171040de8d.jpg)

**Comment by engelen** [comment]
Fixed https://github.com/codepress/admin-columns-pro/commit/4def20f1933f5fb658386bbd635783e2d0c7eae3.
