### ISSUE TITLE
acf JS reference error

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#52]
ReferenceError: acf is not defined on Media screen.

Reproduce: 
1. Enable ACP
2. Go to Media overview
3. Check console

![acf_error](https://cloud.githubusercontent.com/assets/2736280/5523611/f81b6772-89ca-11e4-9ab5-47b3203e303b.jpg)

**Comment by tobiasschutter** [comment]
Triggered by wp_deregister_script( 'jquery-ui-datepicker' ) at cac-addon-inline-edit.php

**Comment by engelen** [comment]
Fixed by simply removing that line; no further issues are caused by this as the datepicker isn't used by Admin Columns at this point.
