### ISSUE TITLE
WooCommerce stock status need inline edit support

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#67]
Stock status need inline edit support.

**Comment by engelen** [comment]
Inline editing is now supported. However, even though it might seem to be so, the stock status column is no simple true/false column, and toggling it can affect more than just the actual stock status. Thus, in some exceptions, the stock status column was made uneditable. In conjunction with fixing qTip2 support, a tooltip should be added to the cell values explaining this.
