### ISSUE TITLE
Column: File location

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#87]
It is possible to add the location of the file? i.e., without the name of the file, and, if possible, cut off by the beginning of the full path (adjustable ), for example: http://selftrips.ru/wp-content/uploads/2013/12/dsc013631.jpg the full path
/2013/12/ location

source: https://wordpress.org/support/topic/add-the-location-of-the-file

**Comment by engelen** [comment]
Done, integrated in the full path column.
