### ISSUE TITLE
Storagemodel gets loaded twice for post (types)

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#88]
set_columns_on_current_screen is called twice when you visit the post type screen. This should only be called once preferably.

1. CPAC_Storage_Model: add_action( 'admin_init', array( $this, 'set_columns_on_current_screen' ) );

2. CPAC_Storage_Model_Post: add_action( 'load-edit.php', array( $this, 'set_columns_on_current_screen' ), 1000 );

To reproduce: Go to the posts listings screen.

**Comment by engelen** [comment]
I remember there being a reason for this, but I can't remember exactly what it was. I believe I introduced this to fix a problem with some external plugins loading there columns quite late (on the load-edit.php action), whilst some other plugins and Admin Columns Pro itself needs the columns to be loaded on admin_init. There might be a better solution, but as is known with WordPress' columns system, there aren't any beautiful solutions to such problems.
