### ISSUE TITLE
WooCommerce Addon: Quick Edit is not working

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#89]
Quick Edit and Bulk Edit feature is not working for products with the add-on active.

class-wc-admin-post-types.php
WC_Admin_Post_Types::bulk_edit()
WC_Admin_Post_Types::quick_edit()

They expect the columns name 'price' to be present. Make sure users can not remove this column type.

The add-on also renames the 'price' column to 'wc-column-price'. This prevents the WC quick edit view from displaying at all.

**Comment by engelen** [comment]
Fixed by changing the way default WooCommerce column extension is handled. The new approach retains original column names, thus offering not only full support of quick edit and bulk edit, but also maintaining proper column styling induced from the original plugin.
